# This is a basic workflow to help you get started with Actions

name: Verify PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      - name: install
        run: yarn 
      - name: lint
        run: yarn eslint src/* \
      - name: build
        run: yarn build
        
      - name: GitHub Checks
        uses: LouisBrunner/checks-action@v1.1.2
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Verify PR
          conclusion: ${{ job.status }}
          output: |
            {"summary":"install: ${{ install.summary }}\nlint: ${{ lint.summary }}\nbuild:${{ build.summary }}"}
